// ============================================================
// XSpan AI Agent — Plugin Architecture v1
// ============================================================
//
// A lightweight plugin system that supports two plugin types:
//
//   1. **Source plugins** — bring data into the system from
//      external devices, APIs, or file formats (e.g., Fitbit,
//      Garmin, CSV import).
//
//   2. **Analyzer plugins** — process biomarker data and
//      produce insights, scores, or nudges (e.g., sleep
//      quality analyzer, cardiovascular trend detector).
//
// ## Developer Guide
//
// To create a plugin:
//   1. Implement the `Plugin` interface (see below).
//   2. Export a factory function that returns your plugin.
//   3. Register it with `PluginManager.register()`.
//
// Plugins are executed in registration order. Source plugins
// run first (to ingest data), then analyzer plugins run
// against the resulting dataset.
//
// ## Lifecycle
//   - `init()` — called once at registration time. Use for
//     setup, config validation, or establishing connections.
//   - `execute(context)` — called each run cycle. Receives
//     a `PluginContext` with the current biomarker snapshots
//     and a way to emit results.
//
// ## Example
//
//   import { PluginManager } from './plugins';
//   import { createFitbitSourcePlugin } from './plugins/examples/fitbit-source';
//   import { createSleepAnalyzerPlugin } from './plugins/examples/sleep-analyzer';
//
//   const manager = new PluginManager();
//   manager.register(createFitbitSourcePlugin({ apiKey: '...' }));
//   manager.register(createSleepAnalyzerPlugin());
//   const results = await manager.executeAnalyzers(snapshots);
//
// ============================================================

import { BiomarkerSnapshot } from '../types/index';

// ── Plugin Types ────────────────────────────────────────────

/** The two categories of plugins supported in v1. */
export type PluginType = 'source' | 'analyzer';

/**
 * Context object passed to plugins during execution.
 *
 * - Source plugins use `context.emit()` to push new snapshots.
 * - Analyzer plugins read `context.snapshots` and return
 *   `AnalyzerResult` from `execute()`.
 */
export interface PluginContext {
  /** Current biomarker snapshots available for analysis. */
  snapshots: BiomarkerSnapshot[];

  /**
   * Emit new snapshots (source plugins only).
   * Analyzer plugins should not call this.
   */
  emit: (snapshot: BiomarkerSnapshot) => void;
}

/**
 * Result returned by analyzer plugins after processing.
 */
export interface AnalyzerResult {
  /** Identifier of the analyzer that produced this result. */
  pluginName: string;
  /** Human-readable insights generated by the analyzer. */
  insights: string[];
  /** Optional numeric scores (e.g., sleep quality 0-100). */
  scores?: Record<string, number>;
  /** Optional metadata for downstream consumers. */
  metadata?: Record<string, unknown>;
}

/**
 * The core Plugin interface that all plugins must implement.
 *
 * @typeParam T - The return type of `execute()`. Source plugins
 *   return `void` (they emit via context). Analyzer plugins
 *   return `AnalyzerResult`.
 */
export interface Plugin<T = AnalyzerResult | void> {
  /** Unique human-readable name for this plugin. */
  name: string;

  /** Semantic version string (e.g., "1.0.0"). */
  version: string;

  /** Whether this plugin is a data source or an analyzer. */
  type: PluginType;

  /**
   * Called once when the plugin is registered.
   * Use for setup, validation, or establishing connections.
   * May be async (e.g., to verify API credentials).
   */
  init(): Promise<void>;

  /**
   * Called each execution cycle.
   *
   * - Source plugins: ingest data and call `context.emit()`.
   * - Analyzer plugins: read `context.snapshots` and return
   *   an `AnalyzerResult`.
   */
  execute(context: PluginContext): Promise<T>;
}

// ── Plugin Manager ──────────────────────────────────────────

/**
 * Manages plugin registration and orchestrated execution.
 *
 * Usage:
 *   const manager = new PluginManager();
 *   manager.register(myPlugin);
 *   const results = await manager.executeAnalyzers(snapshots);
 */
export class PluginManager {
  private _plugins: Plugin<AnalyzerResult | void>[] = [];

  /**
   * Register a plugin. Calls `plugin.init()` during registration.
   * Throws if a plugin with the same name is already registered.
   */
  async register(plugin: Plugin<AnalyzerResult | void>): Promise<void> {
    const existing = this._plugins.find((p) => p.name === plugin.name);
    if (existing) {
      throw new Error(
        `Plugin "${plugin.name}" is already registered. Unregister it first or use a unique name.`,
      );
    }

    await plugin.init();
    this._plugins.push(plugin);
  }

  /**
   * Return all registered plugins, optionally filtered by type.
   */
  getPlugins(type?: PluginType): Plugin<AnalyzerResult | void>[] {
    if (!type) return [...this._plugins];
    return this._plugins.filter((p) => p.type === type);
  }

  /**
   * Execute all registered analyzer plugins against the given
   * snapshots and collect their results.
   *
   * Source plugins are skipped — use `executeSources()` to
   * run those separately.
   *
   * @param snapshots - The biomarker snapshots to analyze
   * @returns Array of AnalyzerResult from each analyzer plugin
   */
  async executeAnalyzers(
    snapshots: BiomarkerSnapshot[],
  ): Promise<AnalyzerResult[]> {
    const analyzers = this._plugins.filter((p) => p.type === 'analyzer');
    const results: AnalyzerResult[] = [];

    for (const analyzer of analyzers) {
      const context: PluginContext = {
        snapshots: [...snapshots],
        emit: () => {
          throw new Error(
            `Analyzer plugin "${analyzer.name}" should not call emit(). Only source plugins emit snapshots.`,
          );
        },
      };

      const result = await analyzer.execute(context);
      if (result) {
        results.push(result as AnalyzerResult);
      }
    }

    return results;
  }

  /**
   * Execute all registered source plugins. Each source plugin
   * receives an `emit()` callback to push new snapshots into
   * the provided array.
   *
   * @param existingSnapshots - Snapshots already in the system (for context)
   * @returns Array of newly emitted BiomarkerSnapshots
   */
  async executeSources(
    existingSnapshots: BiomarkerSnapshot[],
  ): Promise<BiomarkerSnapshot[]> {
    const sources = this._plugins.filter((p) => p.type === 'source');
    const emitted: BiomarkerSnapshot[] = [];

    for (const source of sources) {
      const context: PluginContext = {
        snapshots: [...existingSnapshots],
        emit: (snapshot: BiomarkerSnapshot) => {
          emitted.push(snapshot);
        },
      };

      await source.execute(context);
    }

    return emitted;
  }

  /**
   * Remove a plugin by name.
   * @returns `true` if the plugin was found and removed.
   */
  unregister(name: string): boolean {
    const index = this._plugins.findIndex((p) => p.name === name);
    if (index === -1) return false;
    this._plugins.splice(index, 1);
    return true;
  }
}
